### ISSUE TITLE
Compile errors due to no loop()

### ISSUE THREAD

**Issue by mdlarussa** [BleepLabs/Bleep-Drum#1]

**Comment by BleepLabs** [comment]
Apologies for the confusion. All code has been moved to a directory so opening it in Arduino will be more straightforward.

**Comment by mdlarussa** [comment]
Thanks for responding.  I wasn't sure I'd hear back since the code is over a year old.



I discovered that after I properly cloned the source and imported the whole project into Arduino.  Compiled fine.  Tried to delete the issue, but I guess it stuck around.



For some reason, the hardware isn't working properly now.  I get voltage knocked down to just under 5v at the Mega328's ref pin, but no led or sound.  I don't even get static when plugging in the headphone jack.  Not sure if JCPCB messed something up creating the board from your eagle files or I have a bad component somewhere.





I put it to the side and built a pico paso instead, which worked perfectly.  (I modded it to be able to use a stereo plug though)







---- On Fri, 02 Feb 2018 10:31:19 -0600 Dr. Bleep &lt;notifications@github.com&gt; wrote ----




Apologies for the confusion. All code has been moved to a directory so opening it in Arduino will be more straightforward.

**Comment by BleepLabs** [comment]
There shouldn't be anything connected to aref, pin 21, if that's what you mean. 
7 and 20 should be 5v, 8 and 22 should be ground as seen here. 
https://www.arduino.cc/en/uploads/Hacking/Atmega168PinMap2.png

If you don't have a rail to rail opamp you might not get sound but the LFO LED should always be on.
